import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import MainSection from '../components/SiteSections/MainSection';
import AboutSection from '../components/SiteSections/AboutSection';
import ContactSection from '../components/SiteSections/ContactSection';
import ProjectsSection from '../components/SiteSections/ProjectsSection';

import Footer from '../components/Footer';
import {
  BannerFill,
  ProjectsHeaderWrapper,
} from '../styles/stitches/SiteSection_styles';
import { useInView } from 'react-intersection-observer';
import { useSpring, config } from 'react-spring';

const Home: NextPage = () => {
  const { ref, inView } = useInView();
  const BannerAnimation = useSpring({
    transform: inView ? 'translateX(0%)' : 'translateX(100%)',
    backgroundColor: inView ? 'rgb(3,2,1)' : 'rgb(255, 255, 255)',
  });
  return (
    <>
      <Head>
        <title>Kevin To Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection />
      <AboutSection />
      <ProjectsHeaderWrapper ref={ref}>
        <BannerFill ref={ref} style={BannerAnimation} />
        <h1
          style={{
            color: 'rgb(255, 255, 255)',
            zIndex: '2',
            paddingLeft: '1rem',
            justifySelf: 'center',
          }}
        >
          Projects
        </h1>
      </ProjectsHeaderWrapper>
      <ProjectsSection />
      <ContactSection />
      <Footer />
    </>
  );
};

export default Home;
